// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenDorm.Infrastructure;

#nullable disable

namespace OpenDorm.Infrastructure.Migrations
{
    [DbContext(typeof(OpenDormDbContext))]
    partial class OpenDormDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenDorm.Domain.Aggregates.Dormitory.Dormitory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("идентификатор общежития");

                    b.Property<int>("FloorCount")
                        .HasColumnType("integer")
                        .HasColumnName("floor_count")
                        .HasComment("общее количество этажей в здании");

                    b.HasKey("Id");

                    b.ToTable("dormitories", null, t =>
                        {
                            t.HasComment("общежития");
                        });
                });

            modelBuilder.Entity("OpenDorm.Domain.Aggregates.Dormitory.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("идентификатор комнаты");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity")
                        .HasComment("вместимость");

                    b.Property<Guid>("DormitoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("dormitory_id")
                        .HasComment("идентификатор общежития");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer")
                        .HasColumnName("floor_number")
                        .HasComment("номер этажа");

                    b.Property<char>("Gender")
                        .HasColumnType("character(1)")
                        .HasColumnName("gender")
                        .HasComment("гендер, m - мужская, f - женская");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active")
                        .HasComment("активна ли комната");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name")
                        .HasComment("номер комнаты");

                    b.HasKey("Id");

                    b.HasIndex("DormitoryId");

                    b.ToTable("rooms", null, t =>
                        {
                            t.HasComment("комнаты в общежитиях");

                            t.HasCheckConstraint("CK_Name_MinLength", "LENGTH(name) >= 1");
                        });
                });

            modelBuilder.Entity("OpenDorm.Domain.Aggregates.Occupant.Occupant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("идентификатор жильца");

                    b.Property<byte[]>("BirthDate")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("birth_date_encrypted")
                        .HasComment("зашифрованная дата рождения");

                    b.Property<byte[]>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("bytea")
                        .HasColumnName("first_name_encrypted")
                        .HasComment("зашифрованное имя");

                    b.Property<char>("Gender")
                        .HasColumnType("character(1)")
                        .HasColumnName("gender")
                        .HasComment("гендер (m - мужчина, f - женщина)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("активен ли проживающий, true - да, false - нет");

                    b.Property<byte[]>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("bytea")
                        .HasColumnName("last_name_encrypted")
                        .HasComment("зашифрованная фамилия");

                    b.Property<byte[]>("Patronymic")
                        .HasMaxLength(30)
                        .HasColumnType("bytea")
                        .HasColumnName("patronymic_encrypted")
                        .HasComment("зашифрованное отчество");

                    b.HasKey("Id");

                    b.ToTable("occupants", null, t =>
                        {
                            t.HasComment("жильцы");
                        });
                });

            modelBuilder.Entity("OpenDorm.Domain.Aggregates.Dormitory.Dormitory", b =>
                {
                    b.OwnsOne("OpenDorm.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("DormitoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("address_city")
                                .HasComment("город");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_house")
                                .HasComment("номер дома");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("address_street")
                                .HasComment("улица");

                            b1.HasKey("DormitoryId");

                            b1.ToTable("dormitories", null, t =>
                                {
                                    t.HasCheckConstraint("CK_Address_City_MinLength", "LENGTH(address_city) >= 3");

                                    t.HasCheckConstraint("CK_Address_Street_MinLength", "LENGTH(address_street) >= 3");
                                });

                            b1.WithOwner()
                                .HasForeignKey("DormitoryId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("OpenDorm.Domain.Aggregates.Dormitory.Room", b =>
                {
                    b.HasOne("OpenDorm.Domain.Aggregates.Dormitory.Dormitory", null)
                        .WithMany("_rooms")
                        .HasForeignKey("DormitoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenDorm.Domain.Aggregates.Occupant.Occupant", b =>
                {
                    b.OwnsMany("OpenDorm.Domain.Aggregates.Occupant.Accommodation", "_accommodations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id")
                                .HasComment("идентификатор заселения");

                            b1.Property<DateTime>("CheckInDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("check_in_date")
                                .HasComment("дата и время заселения");

                            b1.Property<DateTime?>("CheckOutDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("check_out_date")
                                .HasComment("дата и время выселения");

                            b1.Property<Guid>("OccupantId")
                                .HasColumnType("uuid")
                                .HasColumnName("occupant_id")
                                .HasComment("идентификатор жильца");

                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id")
                                .HasComment("идентификатор комнаты");

                            b1.HasKey("Id");

                            b1.HasIndex("OccupantId")
                                .HasDatabaseName("UX_Accommodations_OccupantId_Active")
                                .HasFilter("check_out_date IS NULL");

                            b1.HasIndex("RoomId");

                            b1.ToTable("accommodations", null, t =>
                                {
                                    t.HasComment("заселения");
                                });

                            b1.WithOwner()
                                .HasForeignKey("OccupantId");

                            b1.HasOne("OpenDorm.Domain.Aggregates.Dormitory.Room", null)
                                .WithMany()
                                .HasForeignKey("RoomId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.Navigation("_accommodations");
                });

            modelBuilder.Entity("OpenDorm.Domain.Aggregates.Dormitory.Dormitory", b =>
                {
                    b.Navigation("_rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
